// WARNING: FILE CODE GENERATED BY BINDGEN UTILITY. DO NOT EDIT!
/* eslint-disable @typescript-eslint/no-unused-vars */
import { BarretenbergBinder } from '../barretenberg_binder/index.js';
import { BarretenbergWasm } from '../barretenberg_wasm/barretenberg_wasm.js';
import { BoolDeserializer } from '../serialize/index.js';
import { Ptr } from '../types/index.js';

export class BarretenbergApi {
  constructor(public binder: BarretenbergBinder) {}

  static async create(threads: number) {
    const wasm = await BarretenbergWasm.new(threads);
    return new BarretenbergApi(new BarretenbergBinder(wasm));
  }

  async destroy() {
    await this.binder.wasm.destroy();
  }

  async eccNewPippenger(points: Uint8Array, numPoints: number): Promise<Ptr> {
    const result = await this.binder.callWasmExport('ecc_new_pippenger', [points, numPoints], [Ptr]);
    return result[0];
  }

  async eccDeletePippenger(pippenger: Ptr): Promise<void> {
    const result = await this.binder.callWasmExport('ecc_delete_pippenger', [pippenger], []);
    return;
  }

  async examplesSimpleCreateAndVerifyProof(pippenger: Ptr, g2x: Uint8Array): Promise<boolean> {
    const result = await this.binder.callWasmExport(
      'examples_simple_create_and_verify_proof',
      [pippenger, g2x],
      [BoolDeserializer()],
    );
    return result[0];
  }
}
