#!/bin/bash
set -e

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null
IMAGE_URI=278380418400.dkr.ecr.us-east-2.amazonaws.com/barretenberg-wasm-linux-clang:cache-$COMMIT_HASH
docker run -ti --rm $IMAGE_URI