FROM alpine:3.17
RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        bash \
        build-base \
        clang15 \
        cmake \
        ninja \
        git \
        curl \
        perl

WORKDIR /usr/src/barretenberg/cpp

COPY . .