if(MULTITHREADING)
    message(STATUS "Multithreading is enabled.")
    add_compile_options(-pthread)
    add_link_options(-pthread)
else()
    message(STATUS "Multithreading is disabled.")
    add_definitions(-DNO_MULTITHREADING)
    set(OMP_MULTITHREADING OFF)
endif()

if(DISABLE_TBB)
    message(STATUS "Intel Thread Building Blocks is disabled.")
    add_definitions(-DNO_TBB)
else()
    find_package(TBB QUIET OPTIONAL_COMPONENTS tbb)
    if(${TBB_FOUND})
        message(STATUS "Intel Thread Building Blocks is enabled.")
    else()
        message(STATUS "Could not locate TBB.")
        add_definitions(-DNO_TBB)
    endif()
endif()
