[package]
name = "acir-to-bberg-circuit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
serde-big-array = "0.5.1"
flate2 = "1.0"
base64 = "0.13"

acvm = { version = "0.17.0", features = ["bn254"] }
noirc_abi = { git = "https://github.com/noir-lang/noir.git" }
