# Specifically use clang 15 binaries if available. Otherwise fallback on default version.
find_program(CLANG_15 "clang-15")
find_program(CLANGXX_15 "clang++-15")
if (CLANGXX_15)
    message(STATUS "Clang 15 found, using ${CLANGXX_15}...")
    set(CMAKE_C_COMPILER ${CLANG_15})
    set(CMAKE_CXX_COMPILER ${CLANGXX_15})
else()
    find_program(CLANG "clang")
    find_program(CLANGXX "clang++")

    message(STATUS "Clang 15 not found, using ${CLANGXX} instead...")
    set(CMAKE_C_COMPILER ${CLANG})
    set(CMAKE_CXX_COMPILER ${CLANGXX})
endif()
