name: CI

on:
  push:
    branches:
      - jb/bbjs-cra

jobs:
  build-and-deploy:
    name: Build on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install bleeding edge cmake
        run: |
          sudo apt -y remove --purge cmake
          sudo snap install cmake --classic

      - name: Create Build Environment
        run: |
          sudo apt-get update
          sudo apt-get -y install clang ninja-build yarn

      - name: Install yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt -y update && sudo apt -y install yarn

      - name: Compile Barretenberg
        run: |
          cd cpp

          cmake --preset default -DCMAKE_BUILD_TYPE=RelWithAssert
          cmake --build --preset default --target bb

      - name: Compile Typescript
        run: |
          cd ts
          yarn install && yarn && yarn build

      - name: Checkout destination repository
        uses: actions/checkout@v3
        with:
          repository: AztecProtocol/bb.js
          path: ./bb.js
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to destination repository
        run: |
          cd ./bb.js
          cp -R ../ts/dest/* .
          git add .
          git commit -m "Tracking changes"
          git push
