name: Nix builds

on: [push]

jobs:
  nix-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [llvm12, wasm32, cross-aarch64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build barretenberg as ${{ matrix.target }}
        run: |
          nix build -L .#${{ matrix.target }}

      - name: Prepare artifact
        run: |
          mkdir artifacts
          cp -a ./result/. artifacts
          7z a -ttar -so -an ./artifacts/* | 7z a -si ./libbarretenberg.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libbarretenberg-${{ runner.os }}-${{ matrix.target }}.tar.gz
          path: ./libbarretenberg.tar.gz
